version: "3.7"

services:
  database:
    image: postgres
    container_name: database_compasso
    restart: always
    ports:
      - 65432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=compasso
      - POSTGRES_DB=desafio_compasso
    volumes:
      - pgdata:/data/postgres
    
  # app:
  #   build: .
  #   container_name: compasso
  #   restart: always
  #   ports: 
  #     - 3333:3333
  #     - 9229:9229
  #   volumes:
  #     - .:/usr/app
  #   links: 
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata: 
    driver: local